name: Java CI

on:
  push:
    tags:
      - '!release/*'
    branches:
      - '*'
      - '*/*'
      - '**/*'
      - '!release/*'

#################   Build Overview #################
#
#  The Build Process is:
#  1.  Checkout project
#  2.  Install and Deploy the BOM POMs
#  3.  Run tests on Mac and Linux
#  4.  Complete build and run on Linux
#  5.  Deploy from Linux but not Mac (avoid conflicts)
#
#################   Set up Environment  #################
jobs:
  build:

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}



    steps:
      - name: Import GPG Keys
        id: import_gpg
        uses: hashicorp/ghaction-import-gpg@v2.1.0
        env:
          GPG_PRIVATE_KEY: ${{ secrets.SIGNING_KEY }}
          PASSPHRASE: ${{ secrets.SIGNING_PASSWORD }}


      #################   Checkout #################
      #
      #   This step checks out the project
      #
      #################   Checkout #################

    - name: Checkout
      uses: actions/checkout@v1

      #################   JDK  #################
      #
      #     Use JDK 11 to build
      #
      #################   JDK  #################

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: zulu

    #################   Install and Deploy  #################
    #
    #   We're going to deploy the BOM from Ubuntu only
    #   The BOM will be consumed by subsequent test-runs on Ubuntu, Windows, and MacOS
    #
    #################   Install and Deploy  #################



    - name: Install and Deploy Maven POMs
      if: matrix.platform == 'ubuntu-latest'
      run: >-
        mvn install deploy -f bom
        --settings bom/settings/settings.xml
        -Dmaven-repo.github.username=${{secrets.MAVEN_REPOSITORY_USERNAME}}
        -Dmaven-repo.github.password=${{secrets.MAVEN_REPOSITORY_PASSWORD}}


    - name: Install Maven POMs
      run: >-
        mvn install -f bom
        --settings bom/settings/settings.xml
        "-Dmaven-repo.github.username=${{secrets.MAVEN_REPOSITORY_USERNAME}}"
        "-Dmaven-repo.github.password=${{secrets.MAVEN_REPOSITORY_PASSWORD}}"

      #################   Test  #################
      #
      #   Now that the BOM is deployed, lets
      #   run all the tests on all the platforms
      #   for completeness
      #
      #################   Test  #################


    - name: Test on All Platforms
      uses: eskatos/gradle-command-action@v1
      env:
        JAVA_TOOL_OPTIONS: -Duser.language=en -Duser.country=US
      with:
        gradle-version: 7.4
        arguments: >-
          assemble build sA -i
          -PmavenRepositoryUsername=${{secrets.MAVEN_REPOSITORY_USERNAME}}
          -PmavenRepositoryPassword=${{secrets.MAVEN_REPOSITORY_PASSWORD}}
          -PmavenRepositoryUrl=${{secrets.MAVEN_REPOSITORY_URL}} --stacktrace


      #################   Deploy  #################
      #
      # Assuming the tests have passed, deploy from
      # Ubuntu only
      #
      #################   Deploy   #################

    - name: Deploy from Ubuntu
      uses: eskatos/gradle-command-action@v1
      if: matrix.platform == 'ubuntu-latest'
      env:
        JAVA_TOOL_OPTIONS: -Duser.language=en -Duser.country=US
        ORG_GRADLE_PROJECT_SIGNING_KEY: $GPG_PRIVATE_KEY
        ORG_GRADLE_PROJECT_SIGNING_KEY_ID : ${{ secrets.SIGNING_KEY_ID }}
        ORG_GRADLE_PROJECT_SIGNING_PASSWORD : ${{ secrets.SIGNING_PASSWORD }}
      with:
        gradle-version: 7.4
        arguments: >-
          assemble build publish sA signMavenPluginPublication
          -i
          -PmavenRepositoryUsername=${{secrets.MAVEN_REPOSITORY_USERNAME}}
          -PmavenRepositoryPassword=${{secrets.MAVEN_REPOSITORY_PASSWORD}}
          -PmavenRepositoryUrl=${{secrets.MAVEN_REPOSITORY_URL}} --stacktrace
