name: Prepare Arcus Release
on:
  push:
    tags:
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest


    #################   Set up Environment  #################
    #
    #   This is where we set the new MAJOR and MINOR versions
    #   for a series of releases.  This must be updated both
    #   here and in release.yml
    #
    #################   Set up Environment  #################

    env:
      CURRENT_MAJOR_VERSION: 1
      CURRENT_MINOR_VERSION: 41
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    #################   Overview of Build Process   #################
    #   Note:  this is documented fully at
    #   https://github.com/sunshower-io/sunshower-arcus/build.md
    #
    #   Versions:  most/all component versions should be stored in
    #   bom/imported/pom.xml
    #
    #   Released versions:  All exported component versions should be
    #   stored in bom/exported/pom.xml
    #
    #
    #
    #
    #
    #################   Overview of Build Process   #################

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Generate Build Number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{ secrets.github_token }}


      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v5.0.0
        with:
          gpg_private_key: ${{ secrets.SIGNING_KEY }}
          passphrase: ${{ secrets.SIGNING_PASSWORD }}
      #################   Set Final Version Number #################
      # generate the environment variable:
      #     final_version
      #
      # Accessible via ${{ steps.finalVersion.outputs.result }}
      #
      #################   Set Final Version Number #################

      - name: Set Final Version Number
        id: finalVersion
        run: |
          echo ::set-env name=final_version::$CURRENT_MAJOR_VERSION.$CURRENT_MINOR_VERSION.$BUILD_NUMBER
          echo ::set-output name=result::$CURRENT_MAJOR_VERSION.$CURRENT_MINOR_VERSION.$BUILD_NUMBER.Final


      - name: Increment Arcus BOM project version
        run: >-
          mvn versions:set -f bom
          -DnewVersion=${{ steps.finalVersion.outputs.result }}
          --settings bom/settings/settings.xml
          -DnewVersion=${{ steps.finalVersion.outputs.result }}
          -Dmaven-repo.github.username=${{secrets.MAVEN_REPOSITORY_USERNAME}}
          -Dmaven-repo.github.password='${{secrets.MAVEN_REPOSITORY_PASSWORD}}'


      - name: Increment Arcus Property version
        run: >-
          mvn versions:set-property -f bom
          -Dproperty=arcus.version -DnewVersion=${{ steps.finalVersion.outputs.result }}
          --settings bom/settings/settings.xml
          -DnewVersion=${{ steps.finalVersion.outputs.result }}
          -Dmaven-repo.github.username=${{secrets.MAVEN_REPOSITORY_USERNAME}}
          -Dmaven-repo.github.password='${{secrets.MAVEN_REPOSITORY_PASSWORD}}'


      - name: Increment Arcus Build Number
        uses: eskatos/gradle-command-action@v1
        env:
          JAVA_TOOL_OPTIONS: -Duser.language=en -Duser.country=US
        with:
          gradle-version: 7.4
          arguments: >-
            setVersion -DzephyrRelease=true
            -PmavenRepositoryUsername=${{secrets.MAVEN_REPOSITORY_USERNAME}}
            -PmavenRepositoryPassword=${{secrets.MAVEN_REPOSITORY_PASSWORD}}
            -PmavenRepositoryUrl=${{secrets.MAVEN_REPOSITORY_URL}}

      - name: Deploy Bills-Of-Materials
        run: >-
          mvn clean install -f bom
          --settings bom/settings/settings.xml
          -Dmaven-repo.github.username=${{secrets.MAVEN_REPOSITORY_USERNAME}}
          -P github
          -DrepositoryId=github
          -Durl=${{secrets.MAVEN_REPOSITORY_URL}}
          -Dmaven-repo.github.password='${{secrets.MAVEN_REPOSITORY_PASSWORD}}' -e

      - name: Deploy Bills-Of-Materials To Maven Central
        run: >-
          mvn clean install verify deploy
          -f bom
          -P maven-central
          --settings bom/settings/settings.xml
          -Dmaven-repo.github.username=${{secrets.MAVEN_CENTRAL_REPOSITORY_USERNAME}}
          -Dmaven-repo.github.password='${{secrets.MAVEN_CENTRAL_REPOSITORY_PASSWORD}}' -e
          -Dgpg.keyname=${{ secrets.SIGNING_KEY_ID }}
          -Dgpg.passphrase='${{ secrets.SIGNING_PASSWORD }}'



      - name: Build And Deploy Arcus Projects
        uses: eskatos/gradle-command-action@v1
        env:
          JAVA_TOOL_OPTIONS: -Duser.language=en -Duser.country=US
        with:
          gradle-version: 7.4
          arguments: >-
            clean assemble build sA javadoc -i
            -PmavenRepositoryUsername=${{secrets.MAVEN_REPOSITORY_USERNAME}}
            -PmavenRepositoryPassword=${{secrets.MAVEN_REPOSITORY_PASSWORD}}
            -PmavenRepositoryUrl=${{secrets.MAVEN_RELEASE_URL}} --stacktrace



      - name: Deploy To Maven Central
        uses: eskatos/gradle-command-action@v1
        env:
          JAVA_TOOL_OPTIONS: -Duser.language=en -Duser.country=US
        with:
          gradle-version: 7.4
          arguments: >-
            assemble
            build
            sA
            sign
            publish
            -i
            -Psigning.gnupg.keyName=${{ secrets.SIGNING_KEY_ID }}
            -Psigning.gnupg.passphrase=${{ secrets.SIGNING_PASSWORD }}
            -PmavenRepositoryUsername=${{secrets.MAVEN_CENTRAL_REPOSITORY_USERNAME}}
            -PmavenRepositoryPassword=${{secrets.MAVEN_CENTRAL_REPOSITORY_PASSWORD}}
            -PmavenRepositoryUrl=${{secrets.MAVEN_CENTRAL_REPOSITORY_URL}} --stacktrace






      - name: get commit message
        run: echo ::set-env name=commitmsg::$(git log --format=%B -n 1:2 ${{ github.event.after }})


      - name: Commit Version Changes
        run: |
          git config --local user.email "build@sunshower.io"
          git config --local user.name "build"
          git commit -am "Final Release [tag: final, version: ${{steps.finalVersion.outputs.result}}]"

      - name: Perform Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: arcus-${{ env.final_version }}
          release_name: Arcus-release-version-${{ env.final_version }}

          body: |
            ** Changes in arcus-${{ env.final_version }} **

            ${{ env.commitmsg }}

            Tag: https://github.com/sunshower-io/sunshower-arcus/releases/tag/v${{ env.final_version }}.Final
          draft: false
          prerelease: false



      - name: Push Version Changes
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PUSH_ENABLED_GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git tag -a v${{ steps.finalVersion.outputs.result }} -m "Releasing ${{ steps.finalVersion.outputs.result }}"
          git push origin v${{ steps.finalVersion.outputs.result }}



      #################   Rev Snapshots     #################


      - name: Generate Next Number
        id: nextbuildnumber
        uses: einaregilsson/build-number@v2
        with:
          token: ${{ secrets.github_token }}

      # Accessible via ${{ steps.snapshotVersion.outputs.result }}
      - name: Set Next Snapshot Version Number
        id: snapshotVersion
        run: |
          echo '::set-output name=result::$CURRENT_MAJOR_VERSION.$CURRENT_MINOR_VERSION.$BUILD_NUMBER-SNAPSHOT'

      - name: Increment Bills-of-Materials to Snapshots
        run: >-
          mvn versions:set -f bom
          --settings bom/settings/settings.xml
          -DnewVersion=${{ steps.snapshotVersion.outputs.result }}
          -Dmaven-repo.github.username=${{secrets.MAVEN_REPOSITORY_USERNAME}}
          -Dmaven-repo.github.password='${{secrets.MAVEN_REPOSITORY_PASSWORD}}'
          &&
          mvn versions:set-property -f bom
          --settings bom/settings/settings.xml
          -Dproperty=arcus.version -DnewVersion=${{ steps.snapshotVersion.outputs.result }}
          -Dmaven-repo.github.username=${{secrets.MAVEN_REPOSITORY_USERNAME}}
          -Dmaven-repo.github.password='${{secrets.MAVEN_REPOSITORY_PASSWORD}}'
          &&
          mvn clean install -f bom
          --settings bom/settings/settings.xml
          -Dmaven-repo.github.username=${{secrets.MAVEN_REPOSITORY_USERNAME}}
          -Dmaven-repo.github.password='${{secrets.MAVEN_REPOSITORY_PASSWORD}}'

      - name: Increment Arcus Build Number to Snapshot
        uses: eskatos/gradle-command-action@v1
        env:
          JAVA_TOOL_OPTIONS: -Duser.language=en -Duser.country=US
        with:
          gradle-version: 7.4
          arguments: >-
            setVersion -PmavenRepositoryUsername=${{secrets.MAVEN_REPOSITORY_USERNAME}}
            -PmavenRepositoryPassword=${{secrets.MAVEN_REPOSITORY_PASSWORD}}
            -PmavenRepositoryUrl=${{secrets.MAVEN_REPOSITORY_URL}}

      - name: Deploy Bills-Of-Materials
        run: >-
          mvn install -f bom
          --settings bom/settings/settings.xml
          -Dmaven-repo.github.username=${{secrets.MAVEN_REPOSITORY_USERNAME}}
          -Dmaven-repo.github.password='${{secrets.MAVEN_REPOSITORY_PASSWORD}}' -e



      - name: Build Arcus Projects
        uses: eskatos/gradle-command-action@v1
        env:
          JAVA_TOOL_OPTIONS: -Duser.language=en -Duser.country=US
        with:
          gradle-version: 7.4
          arguments: >-
            clean assemble build sA javadoc -i
            -PmavenRepositoryUsername=${{secrets.MAVEN_REPOSITORY_USERNAME}}
            -PmavenRepositoryPassword=${{secrets.MAVEN_REPOSITORY_PASSWORD}}
            -PmavenRepositoryUrl=${{secrets.MAVEN_REPOSITORY_URL}} --stacktrace



      - name: Commit Version Changes and Release
        run: |
          git config --local user.email "build@sunshower.io"
          git config --local user.name "build"
          git remote set-url origin https://x-access-token:${{ secrets.PUSH_ENABLED_GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Releasing new Snapshot [tag: snapshot]"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUSH_ENABLED_GITHUB_TOKEN }}

      - name: Delete release tag
        run: |
          git push --delete origin release/${GITHUB_REF##*/}
